---
version: '3.2'

services:

  jenkins:
    container_name: jenkins
    build:
      context: jenkins-docker
      args: 
        DOCKER_GID: ${DOCKER_GID:-300}
    image: mikeascott/jenkins-docker:lts

    ports:
      - 8088:8088
      - 50000:50000
    
    environment:
      JENKINS_OPTS: '--httpPort=8088'

    networks:
      jenkins:

    volumes:
      - type: volume
        source: jenkins-data
        target: /var/jenkins_home
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock

networks: 
  jenkins:

volumes:
 jenkins-data: